In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
! pip install impyute

In [5]:
import pandas as pd
import numpy as np
import datetime as dt
import re
import matplotlib.pyplot as plt
from tqdm import tqdm
import seaborn as sns
import xgboost as xgb
from xgboost import plot_importance
from sklearn.metrics import *
from sklearn.model_selection import KFold
import warnings
import lightgbm as lgb
warnings.filterwarnings(action='ignore')
from impyute.imputation.cs import mice
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [6]:
train_err = pd.read_csv('/content/drive/MyDrive/데이콘/data/train_err_data.csv')
train_problem = pd.read_csv('/content/drive/MyDrive/데이콘/data/train_problem_data.csv')
test_err = pd.read_csv('/content/drive/MyDrive/데이콘/data/test_err_data.csv')
sample_submission = pd.read_csv('/content/drive/MyDrive/데이콘/data/sample_submission.csv')
train_quality = pd.read_csv('/content/drive/MyDrive/데이콘/data/train_quality_data.csv')
test_quality = pd.read_csv('/content/drive/MyDrive/데이콘/data/test_quality_data.csv')

In [7]:
train_err.head()

user_id            time model_nm       fwver  errtype errcode
0    10000  20201101025616  model_3  05.15.2138       15       1
1    10000  20201101030309  model_3  05.15.2138       12       1
2    10000  20201101030309  model_3  05.15.2138       11       1
3    10000  20201101050514  model_3  05.15.2138       16       1
4    10000  20201101050515  model_3  05.15.2138        4       0

In [8]:
train_user_id_max = 24999
train_user_id_min = 10000
train_user_number = 15000

In [9]:
id_error = train_err[['user_id','errtype']].values
error = np.zeros((train_user_number,42))

for person_idx, err in tqdm(id_error):
  error[person_idx-train_user_id_min,err-1] +=1
error

100%|██████████| 16554663/16554663 [00:46<00:00, 357684.72it/s]


array([[  0.,   0.,   8., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ..., 113.,  56.,   1.],
       [  0.,   0.,   2., ...,   0.,   0.,   0.],
       ...,
       [  0.,   0.,   0., ...,  58.,   8.,   5.],
       [  0.,   0.,   0., ...,   6.,   0.,   0.],
       [  0.,   0.,   4., ...,   0.,   0.,   0.]])

In [10]:
problem = np.zeros(15000)
problem[train_problem['user_id'].unique()-train_user_id_min] = 1
problem

array([0., 1., 0., ..., 1., 1., 0.])

In [11]:
train_err_df = pd.DataFrame(error)
train_err_df

0    1    2      3     4    5   ...   36   37   38     39    40   41
0      0.0  0.0  8.0  104.0   0.0  1.0  ...  0.0  0.0  0.0    0.0   0.0  0.0
1      0.0  0.0  0.0    0.0  53.0  1.0  ...  1.0  0.0  0.0  113.0  56.0  1.0
2      0.0  0.0  2.0  132.0   1.0  2.0  ...  0.0  0.0  0.0    0.0   0.0  0.0
3      0.0  0.0  0.0    0.0   2.0  1.0  ...  1.0  2.0  0.0   17.0   1.0  0.0
4      0.0  0.0  0.0    1.0   0.0  3.0  ...  1.0  0.0  0.0    4.0   0.0  2.0
...    ...  ...  ...    ...   ...  ...  ...  ...  ...  ...    ...   ...  ...
14995  0.0  0.0  0.0    0.0   2.0  5.0  ...  0.0  0.0  0.0    9.0   7.0  4.0
14996  0.0  0.0  0.0    0.0   0.0  0.0  ...  0.0  0.0  0.0    0.0   0.0  0.0
14997  0.0  0.0  0.0    1.0   8.0  1.0  ...  1.0  0.0  0.0   58.0   8.0  5.0
14998  0.0  0.0  0.0    0.0   0.0  0.0  ...  1.0  0.0  0.0    6.0   0.0  0.0
14999  0.0  0.0  4.0  192.0   7.0  5.0  ...  0.0  0.0  0.0    0.0   0.0  0.0

[15000 rows x 42 columns]

In [13]:
x = StandardScaler().fit_transform(train_err_df.values)
features = list(range(0,42,1))
pd.DataFrame(x,columns=features).head()

0         1         2   ...        39        40        41
0 -0.196898 -0.030123  0.084345  ... -0.602484 -0.297800 -0.644056
1 -0.196898 -0.030123 -0.029070  ...  0.795711  2.104322 -0.363005
2 -0.196898 -0.030123 -0.000716  ... -0.602484 -0.297800 -0.644056
3 -0.196898 -0.030123 -0.029070  ... -0.392136 -0.254905 -0.644056
4 -0.196898 -0.030123 -0.029070  ... -0.552991 -0.297800 -0.081954

[5 rows x 42 columns]

In [72]:
pca = PCA(n_components=35)
printcipalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data=printcipalComponents)
principalDf.head()

0         1         2   ...        32        33        34
0 -1.900356 -0.180681  0.661727  ... -0.003408 -0.060427  0.010199
1  5.169480 -0.895393  5.645860  ...  0.026529 -0.832355  0.014435
2 -2.059069 -0.253401  0.754751  ...  0.053559 -0.062375  0.030866
3 -0.406911 -0.182769 -0.225277  ...  0.033049  0.096597 -0.012614
4  0.249358 -0.053803 -0.575960  ... -0.033557  0.071578 -0.036750

[5 rows x 35 columns]

In [73]:
pca.explained_variance_ratio_

array([0.10372063, 0.07610478, 0.07352561, 0.06210993, 0.05191624,
       0.05119222, 0.04102495, 0.0310046 , 0.02672474, 0.02587593,
       0.02515257, 0.02472248, 0.02457164, 0.02422904, 0.0241223 ,
       0.02393213, 0.02381464, 0.02290001, 0.02274434, 0.02212234,
       0.02202927, 0.02192162, 0.02170203, 0.02060562, 0.01923957,
       0.01852873, 0.01754507, 0.01702237, 0.01438544, 0.01149707,
       0.00892944, 0.00880045, 0.0076154 , 0.00435637, 0.00171544])

In [74]:
sum(pca.explained_variance_ratio_)

0.9974050161906398

In [75]:
train_x = principalDf.values
train_y = problem
print(train_x.shape)
print(train_y.shape)

(15000, 35)
(15000,)


In [76]:
# dtrain = xgb.DMatrix(data=train_x,label=train_y)

In [77]:
def f_pr_auc(probas_pred, y_true):
    labels=y_true.get_label()
    p, r, _ = precision_recall_curve(labels, probas_pred)
    score=auc(r,p) 
    return "pr_auc", score, True
#-------------------------------------------------------------------------------------
models     = []
recalls    = []
precisions = []
auc_scores   = []
threshold = 0.5
# 파라미터 설정
params =      {
                'boosting_type' : 'gbdt',
                'objective'     : 'binary',
                'metric'        : 'auc',
                'seed': 1015
                }
#-------------------------------------------------------------------------------------
# 5 Kfold cross validation
k_fold = KFold(n_splits=5, shuffle=True, random_state=42)
for train_idx, val_idx in k_fold.split(train_x):

    # split train, validation set
    X = train_x[train_idx]
    y = train_y[train_idx]
    valid_x = train_x[val_idx]
    valid_y = train_y[val_idx]

    d_train= lgb.Dataset(X, y)
    d_val  = lgb.Dataset(valid_x, valid_y)
    
    #run traning
    model = lgb.train(
                        params,
                        train_set       = d_train,
                        num_boost_round = 1000,
                        valid_sets      = d_val,
                        feval           = f_pr_auc,
                        verbose_eval    = 20, 
                        early_stopping_rounds = 50
                       )
    
    # cal valid prediction
    valid_prob = model.predict(valid_x)
    valid_pred = np.where(valid_prob > threshold, 1, 0)
    
    # cal scores
    recall    = recall_score(    valid_y, valid_pred)
    precision = precision_score( valid_y, valid_pred)
    auc_score = roc_auc_score(   valid_y, valid_prob)

    # append scores
    models.append(model)
    recalls.append(recall)
    precisions.append(precision)
    auc_scores.append(auc_score)

    print('==========================================================')

Training until validation scores don't improve for 50 rounds.
[20]	valid_0's auc: 0.783532	valid_0's pr_auc: 0.775152
[40]	valid_0's auc: 0.786987	valid_0's pr_auc: 0.777936
[60]	valid_0's auc: 0.787491	valid_0's pr_auc: 0.779583
[80]	valid_0's auc: 0.786829	valid_0's pr_auc: 0.778687
Early stopping, best iteration is:
[35]	valid_0's auc: 0.787524	valid_0's pr_auc: 0.778634
Training until validation scores don't improve for 50 rounds.
[20]	valid_0's auc: 0.792444	valid_0's pr_auc: 0.338502
[40]	valid_0's auc: 0.795289	valid_0's pr_auc: 0.377945
[60]	valid_0's auc: 0.79084	valid_0's pr_auc: 0.36369
Early stopping, best iteration is:
[28]	valid_0's auc: 0.795654	valid_0's pr_auc: 0.365128
Training until validation scores don't improve for 50 rounds.
[20]	valid_0's auc: 0.760268	valid_0's pr_auc: 0.359205
[40]	valid_0's auc: 0.757692	valid_0's pr_auc: 0.358495
[60]	valid_0's auc: 0.754636	valid_0's pr_auc: 0.362256
Early stopping, best iteration is:
[19]	valid_0's auc: 0.76067	valid_0's p

In [78]:
# 교차검증 점수 확인
print(np.mean(auc_scores))

0.7873509132340919


In [79]:
test_user_id_max = 44998
test_user_id_min = 30000
test_user_number = 14999

In [80]:
id_error = test_err[['user_id','errtype']].values
test_x = np.zeros((test_user_number,42))
for person_idx, err in tqdm(id_error):
  test_x[person_idx-test_user_id_min,err-1]+=1
test_x = test_x.reshape(test_x.shape[0],-1)
test_x.shape

100%|██████████| 16532648/16532648 [00:43<00:00, 376581.46it/s]


(14999, 42)

In [83]:
x = StandardScaler().fit_transform(test_x)
features = list(range(0,42,1))
pd.DataFrame(x,columns=features).head()

0         1         2   ...        39        40        41
0 -0.195744 -0.031265 -0.053584  ...  0.539586 -0.347358 -0.081558
1 -0.195744 -0.031265  0.049534  ... -0.602543 -0.347358 -0.644892
2 -0.195744 -0.031265 -0.053584  ...  0.800289 -0.299226 -0.081558
3 -0.195744 -0.031265 -0.053584  ... -0.105965  0.037700 -0.644892
4 -0.195744 -0.031265 -0.053584  ... -0.006650  3.984542 -0.644892

[5 rows x 42 columns]

In [84]:
pca = PCA(n_components=35)
printcipalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data=printcipalComponents)
principalDf.head()

0         1         2   ...        32        33        34
0  3.849484  0.153335 -0.209856  ... -0.096499 -1.249104 -0.017040
1 -1.717129  1.238631  0.254041  ...  0.018128  0.022877  0.073729
2  0.841724 -1.153780 -0.354981  ... -0.003277  0.154757 -0.024570
3 -0.304580  1.589680  0.066170  ...  0.067945 -1.078473  0.005050
4  0.086201 -0.381751 -0.153945  ...  0.049505  0.209458  0.013321

[5 rows x 35 columns]

In [85]:
pca.explained_variance_ratio_

array([0.10551963, 0.08162703, 0.07311925, 0.05974668, 0.0497546 ,
       0.04769242, 0.04078267, 0.03342663, 0.02903789, 0.0272462 ,
       0.0261853 , 0.0257028 , 0.02513293, 0.02475112, 0.02446356,
       0.02419554, 0.02389938, 0.02376061, 0.02334725, 0.02253779,
       0.02163606, 0.0209082 , 0.02022888, 0.01960898, 0.01924298,
       0.0188393 , 0.01766938, 0.01464292, 0.0129419 , 0.00972553,
       0.00829456, 0.00701778, 0.00602711, 0.00467218, 0.00252615])

In [86]:
sum(pca.explained_variance_ratio_)

0.9959111937822308

In [87]:
# 예측
pred_y_list =[]
for model in models:
  pred_y = model.predict(principalDf.values)
  pred_y_list.append(pred_y.reshape(-1,1))
pred_ensemble = np.mean(pred_y_list,axis=0)
pred_ensemble

array([[0.82171917],
       [0.44733971],
       [0.40593259],
       ...,
       [0.5870313 ],
       [0.77768075],
       [0.39675313]])

In [88]:
pred = np.where(pred_ensemble>threshold, 1,0)
pred

array([[1],
       [0],
       [0],
       ...,
       [1],
       [1],
       [0]])

In [ ]:
sample_submission.head(2)

user_id  problem
0    30000        0
1    30001        0

In [89]:
sample_submission['problem'] = pred
sample_submission.head()

user_id  problem
0    30000        1
1    30001        0
2    30002        0
3    30003        0
4    30004        0

In [90]:
sample_submission.to_csv('/content/drive/MyDrive/데이콘/submission/lgb_kfold5_only_errordata_pca35_submission_threshold0.5.csv')